# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: arm64-qemu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        arch: [arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Check out code
      uses: actions/checkout@v4

    - name: Go mod tidy
      run: go mod tidy

    - name: Test
      run: go test -v -short ./...
      env:
        DISABLE_SM3NI: 1
        GODEBUG: x509sha1=1
        GOARCH: ${{ matrix.arch }}
