name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
    contents: write
    packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goVer: ['1.21', '1.24']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.goVer }}

      - name: Go mod tidy
        run: go mod tidy

      - name: Test with Coverage
        if: ${{ matrix.goVer == '1.24' }}
        run: go test -coverpkg=./... -v -short -race -coverprofile=cover.out -covermode=atomic ./...
        env:
          GODEBUG: x509sha1=1

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.goVer == '1.24' }}
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: cover.out

      - name: Test only
        if: ${{ matrix.goVer != '1.24' }}
        run: go test -short ./...
        env:
          GODEBUG: x509sha1=1

      - name: Test Generic only
        if: ${{ matrix.goVer != '1.24' }}
        run: go test -short -tags purego ./...
        env:
          GODEBUG: x509sha1=1
