# 登陆
Passport:
  # 密码全局盐
  PasswordSalt: "e6c2ea864004a461e744b28a394df50c"
  # 验证码字段
  HeaderCaptchaKey: "Lakego-Admin-Captcha-Id"
  AccessTokenId: "lakego-passport-access-token"
  AccessExpiresIn: 86400
  RefreshTokenId: "lakego-passport-refresh-token"
  RefreshExpiresIn: 604800

# jwt 相关
Jwt:
  Iss: "admin-api.yourdomain.com"
  Aud: "lakego-admin"
  Sub: "lakego-admin-passport"
  Jti: "lakego-admin-jid"
  Exp: 3600
  Nbf: 0

  # 使用签名方式
  # HS256,HS384,HS512; ES256,ES384,ES512;
  # RS256,RS384,RS512; PS256,PS384,PS512;
  # EdDSA;
  SigningMethod: "HS256"
  # 密码，base64 编码后，适用类型 HS
  Secret: "MTIzNDU2"
  # 公钥和私钥，适用类型 ES, RS, PS, EdDSA
  PrivateKey: "{root}/config/key/rsa/private_key.pem"
  PublicKey: "{root}/config/key/rsa/public_key.pem"
  # 私钥密码，base64 编码后，适用类型 RS
  PrivateKeyPassword: "MTIzNDU2"
  # 载荷加密秘钥，为空或者 base64 后解码错误不加密，base64编码后
  Passphrase: "YTY5YmNiZTgxMzVhMWY2MTA3Njc3NGY1YTE3MWI2MjQ="

# 权限
Auth:
  # 登陆过滤 ["GET:passport/login"]
  AuthenticateExcepts: []
  # 权限过滤 ["GET:passport/login"]
  PermissionExcepts: []
  # 超级管理员
  AdminId: "e92ba0a3f86f4a5693d8487eb8c632b5"
