# 默认缓存
default: "redis"

# 前缀
key-prefix: "lakego-cache"

# 缓存列表
caches:
  redis:
    type: "redis"
    addr: "127.0.0.1:6379"
    password: "admin123"
    db: 1
    minidle-conn: 200
    dial-timeout: 60s
    read-timeout: 500ms
    write-timeout: 500ms
    # 启用的连接池数量
    pool-size: 10
    pool-timeout: 240s
    enabletrace: false

