# 默认缓存
default: "redis"

# 缓存列表
caches:
  redis:
    type: "redis"
    prefix: "cache"
    db: 1
    addr: "127.0.0.1:6379"
    password: "admin123"
    minidle-conn: 200
    dial-timeout: 60s
    read-timeout: 500ms
    write-timeout: 500ms
    pool-size: 100
    pool-timeout: 240s
    enabletrace: false

