# 默认缓存
Default: "redis"

# 缓存列表
Caches:
  Redis:
    Type: "redis"
    Prefix: "cache"
    DB: 1
    Addr: "127.0.0.1:6379"
    Password: "admin123"
    MinIdleConn: 200
    DialTimeout: 60s
    ReadTimeout: 500ms
    WriteTimeout: 500ms
    PoolSize: 100
    PoolTimeout: 240s
    Enabletrace: false

