# 验证码配置
Captcha:
    Height: 46
    Width: 140
    NoiseCount: 2
    ShowLineOptions: 2
    # 长度
    Length: 4
    # 随机数
    Source: "234567890abcdefghjkmnpqrstuvwxyz"
    # 字体
    Fonts: "wqy-microhei.ttc"
    # 颜色
    RGBA:
      R: 240
      G: 240
      B: 246
      A: 246

# 默认存储
DefaultStore: "redis"
# 存储列表
Stores:
  # redis 存储配置
  Redis:
    # 类型
    Type: "redis"
    # 前缀
    Prefix: "captcha"
    # 过期时间
    Ttl: 3600
    # redis 使用数据库
    Db: 1
    # 地址
    Addr: "127.0.0.1:6379"
    # 密码
    Password: "admin123"


