# 跨域响应
open-allow-origin: true
allow-origin: "*"
allow-credentials: true
allow-methods: "GET,POST,PATCH,PUT,DELETE,OPTIONS"
allow-headers: "X-Requested-With,X_Requested_With,Content-Type,Authorization,Lakego-Admin-Captcha-Id"
expose-headers: "Lakego-Admin-Captcha-Id"
max-age: ""
