# 默认
default: "mysql"

# true or false
debug: false

# 连接列表
connections:
  mysql:
    type: "mysql"
    # 填写替换其他配置
    dsn: ""
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "123456"
    database: "lakego_admin"
    charset: "utf8mb4"
    prefix: "lakego_"
    max-idle-conns: 10
    max-open-conns: 128
    conn-max-lifetime: 60      # 连接不活动时的最大生存时间(秒)
    #reconnectinterval: 1    # 保留项,重连数据库间隔秒数
    #pingfailretrytimes: 3   # 保留项,最大重连次数
