# 默认磁盘
Default: "public"

# 磁盘列表
Disks:
    Local:
        # 磁盘类型
        Type: "local"
        # 磁盘路径
        Root: "{storage}/app/attach"

    Public:
        # 磁盘类型
        Type: "local"
        # 磁盘路径
        Root: "{public}/storage"
        # 磁盘路径对应的外部URL路径
        Url: "http://lakego-storage.storage1000.com/storage"
        # 可见性
        Visibility: "public"

# 软连接
# 可执行脚本 "go run main.go lakego:storage-link" 创建
Links:
    # to : from
    - "{public}/storage:{storage}/app/public"
