# 默认磁盘
default: "public"

# 磁盘列表
disks:
    local:
        # 磁盘类型
        type: "local"
        # 磁盘路径
        root: "{storage}/app/attach"

    public:
        # 磁盘类型
        type: "local"
        # 磁盘路径
        root: "{storage}/app/public"
        # 磁盘路径对应的外部url路径
        url: "http://127.0.0.1:8080/storage"
        # 可见性
        visibility: "public"

# 软连接
# 可执行脚本 "go run main.go lakego:storage-link" 创建
links:
    # to : from
    - "{public}/storage:{storage}/app/public"
