# 默认驱动
default: "logrus"

# 驱动列表
drivers:
  # logrus 日志驱动
  logrus:
    # 类型
    type: "logrus"
    # 格式化类型 normal, json, text
    formatter: "normal"
    # 设置最低 loglevel.
    # 包括："panic", "fatal", "error", "warning", "info", "debug", "trace"
    level: "trace"
    # 日志存储位置
    filepath: "{runtime}/log/log_%Y%m%d.log"
    # MaxAge
    max-age: 168
    # 单位：小时
    rotation-time: 24
