# 默认驱动
Default: "logrus"

# 驱动列表
Drivers:
  # logrus 日志驱动
  Logrus:
    # 类型
    Type: "logrus"
    # 格式化类型 normal, json, text
    Formatter: "normal"
    # 设置最低 loglevel.
    # 包括："panic", "fatal", "error", "warning", "info", "debug", "trace"
    Level: "trace"
    # 日志存储位置
    Filepath: "{root}/runtime/log"
    # MaxAge
    MaxAge: 168
    # 单位：小时
    RotationTime: 24
