# 默认
default: "redis"

# 连接列表
connects:
  # redis
  redis:
    db: 1
    addr: "127.0.0.1:6379"
    password: "admin123"
    minidle-conn: 200
    dial-timeout: 60s
    read-timeout: 500ms
    write-timeout: 500ms
    # 启用的连接池数量
    pool-size: 20
    pool-timeout: 240s
    enabletrace: false
    key-prefix: "lakego-redis"
