# 运行链接
Url: "127.0.0.1:8080"

# 运行方式
Default: "Http"
Types:
  # tcp请求
  Http:
    Port: ":8080"

  # https
  TLS:
    Port: ":8080"
    CertFile: "{root}/config/server/certFile.pem"
    KeyFile: "{root}/config/server/keyFile.pem"

  # Unix
  Unix:
    File: "{root}/config/server/unix.pid"

  # Fd
  Fd:
    Fd: 1

  # 自定义监听
  NetListener:
    Type: "tcp"
    Port: ":8080"
