# 运行链接
Url: "127.0.0.1:8080"

# 配置模式 lakegodev | dev | release
Mode: "dev"

# 日志记录方式 file | stdout
LogType: "stdout"

# 运行方式
Default: "Http"
Types:
  # tcp请求
  Http:
    # 运行地址
    Addr: ":8080"
    # 运行方式 gin | grace
    Servertype: "grace"

  # https
  TLS:
    # 运行地址
    Addr: ":8080"
    CertFile: "{root}/config/server/certFile.pem"
    KeyFile: "{root}/config/server/keyFile.pem"

  # Unix
  Unix:
    File: "{root}/config/server/unix.pid"

  # Fd
  Fd:
    Fd: 1

  # 自定义监听
  NetListener:
    Type: "tcp"
    Addr: ":8080"
