# 配置模式 dev | release
mode: "dev"

# 日志记录方式 file | stdout
log-type: "stdout"

# 日志显示方式 lakego | gin
log-show-type: "gin"

# 命令行显示时使用
server-url: "http://127.0.0.1:8080"

# 运行方式
default: "http"
types:
  # tcp请求
  http:
    # 运行地址
    addr: ":8080"
    # 运行方式 gin | grace
    server-type: "grace"
    # 读取超时时间
    grace-read-timeout: "20s"
    # 读取超时时间
    grace-write-timeout: "20s"
    # 超时时间
    grace-timeout: "5s"

  # https
  tls:
    # 运行地址
    addr: ":8080"
    cert-file: "{config}/server/certFile.pem"
    key-file: "{config}/server/keyFile.pem"

  # unix
  unix:
    file: "{config}/server/unix.pid"

  # fd
  fd:
    fd: 1

  # 自定义监听
  net-listener:
    type: "tcp"
    addr: ":8080"
