# 默认签名
default: "md5"

# 驱动列表
crypts:
  # md5
  md5:
    type: "md5"
    key: "dfertf12dfertf12"
    # 签名方式： 链接 query, 加密函数用 signkey
    signtype: "query"

  # sha1
  sha1:
    type: "sha1"
    key: ""
    signtype: "query"

  # hmac 摘要
  hmac:
    type: "hmac"
    key: ""
    signtype: "signkey"

  # aes 对称加密
  aes:
    type: "aes"
    key: "dfertf12dfertf12"
    iv: "dfertf12dfertf12"
    signtype: "signkey"

  # rsa 非对称加密
  rsa:
    type: "rsa"
    # 公钥
    publickey: ""
    # 私钥
    privatekey: ""
    signtype: "signkey"

  # bcrypt 摘要
  bcrypt:
    type: "bcrypt"
    key: ""
    signtype: "query"

